### ISSUE TITLE
TWW Prepatch errors

### ISSUE THREAD

**Issue by Hampen555** [eltreum0/DailtyToDoContinued#3]
Hi, I love this addon and would be very happy if these prepatch errors got fixed, thanks :)

### Error 1, on login
`1x DailyToDo/DailyToDo.lua:809: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@DailyToDo/DailyToDo.lua"]:809: in function `CreateManagerFrame'
[string "@DailyToDo/DailyToDo.lua"]:223: in function <DailyToDo/DailyToDo.lua:206>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventoryClient.lua"]:898: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13105: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13128: in function `BlizzardAPIHook'
[string "@ArkInventory/Core/ArkInventory.lua"]:3102: in function <ArkInventory/Core/ArkInventory.lua:3058>
...
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
self = <table> {
 checklistFrameHeaderExpandPool = <table> {
 }
 checklistManagerFrame = ChecklistManagerFrame {
 }
 modules = <table> {
 }
 icon = <table> {
 }
 defaultModuleState = true
 currentDay = 4
 data = <table> {
 }
 checklistFrameHeaderTextPool = <table> {
 }
 enabledState = true
 maxEntries = 10
 db = <table> {
 }
 baseName = "DailyToDo"
 checklistFrameHeaderCheckboxPool = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 DailyToDoLDB = <table> {
 }
 name = "DailyToDo"
 orderedModules = <table> {
 }
 defaults = <table> {
 }
 managerPanelHeight = 300
 localize = <table> {
 }
 checklistFrameTextPool = <table> {
 }
 selectedEntryColor = "|cffFFB90F"
 timerId = <table> {
 }
 checklistFrameCheckboxPool = <table> {
 }
}
(*temporary) = nil
(*temporary) = ChecklistManagerFrame {
 name = "DailyToDo"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"
isRetail = true
`
### Error 2, when i typed /todo options
`4x DailyToDo/DailyToDo.lua:171: attempt to call global 'InterfaceOptionsFrame_OpenToCategory' (a nil value)
[string "@DailyToDo/DailyToDo.lua"]:171: in function `?'
[string "@Ace3/AceConsole-3.0-7/AceConsole-3.0.lua"]:90: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5440: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5386>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5092: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5091>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5128: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
self = <table> {
 checklistFrameHeaderExpandPool = <table> {
 }
 checklistManagerFrame = ChecklistManagerFrame {
 }
 modules = <table> {
 }
 icon = <table> {
 }
 defaultModuleState = true
 currentDay = 4
 data = <table> {
 }
 checklistFrameHeaderTextPool = <table> {
 }
 enabledState = true
 maxEntries = 10
 db = <table> {
 }
 baseName = "DailyToDo"
 checklistFrameHeaderCheckboxPool = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 DailyToDoLDB = <table> {
 }
 name = "DailyToDo"
 orderedModules = <table> {
 }
 defaults = <table> {
 }
 managerPanelHeight = 300
 localize = <table> {
 }
 checklistFrameTextPool = <table> {
 }
 selectedEntryColor = "|cffFFB90F"
 timerId = <table> {
 }
 checklistFrameCheckboxPool = <table> {
 }
}
msg = "options"
command = "options"
text = ""
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to call global 'InterfaceOptionsFrame_OpenToCategory' (a nil value)"
`

**Comment by xPainee** [comment]
I hope a fix is coming soon, miss this addon :(
